project: 
  type: website

format:
  html:
    code-fold: true
    code-tools: true
    toc: true
    toc-depth: 5
    toc-location: right
    theme: [united, theme.scss]
    css: styles.css
    self-contained: true
    link-external-newwindow: true
    link-external-icon: false
    backgroundcolor: "#F8F7F0"

knitr: 
  opts_chunk: 
    comment: "#>"
    fig.align: "center"
    fig.show: "hold"
    fig.asp: 0.618
    fig.retna: 3
    fig.path: figs/
    out.width: 70%

execute: 
  freeze: false
  warning: false

website: 
  title: "PEV Project"
  repo-url: https://github.com/jhelvy/pingfan
  repo-actions: [edit, issue]
  sidebar: 
    style: docked
    background: light
    collapse-level: 1
    search: true
    contents: 
      - text: Home
        icon: house-door-fill
        href: index.qmd
      - section: Project
        icon: pencil-square
        contents: 
          - text: 1. Project Proposal
            href: qmd_project/01_project_proposal.qmd